CHANNELS = [
    # ── Galaxy Main ──────────────────────────────────────────────
    {
        "number": 100, "name": "Galaxy ONE", "tier": "Galaxy Main",
        "vibe": "Flagship / Big Tent", "mode": "Flex",
        "style": "Curated best-of — hand-picked, every slot intentional",
        "dayparts": {
            "Early Morning (6-9AM)": "Feel-good movies, light drama",
            "Morning (9AM-12PM)": "Acclaimed series block",
            "Afternoon (12-5PM)": "Movie double features",
            "Prime Time (5-10PM)": "FLAGSHIP PREMIERES — best movies & series",
            "Late Night (10PM-2AM)": "Prestige drama, award-winning films",
            "Overnight (2-6AM)": "Encore block (prime time replay)",
        },
        "recommended": "Oscar winners, critically acclaimed films, best of every genre",
        "color": "blue",
    },
    {
        "number": 101, "name": "Galaxy 2", "tier": "Galaxy Main",
        "vibe": "Everyday cable comfort", "mode": "Shuffle",
        "style": "The 'always on' channel — comfortable, familiar, zero commitment",
        "dayparts": {
            "Early Morning (6-9AM)": "Sitcom reruns (light, easy)",
            "Morning (9AM-12PM)": "Procedural block (NCIS, Law & Order)",
            "Afternoon (12-5PM)": "Afternoon movie (mainstream hit)",
            "Prime Time (5-10PM)": "Prime mix — popular sitcoms + procedurals",
            "Late Night (10PM-2AM)": "Crime procedurals, drama reruns",
            "Overnight (2-6AM)": "Overnight reruns",
        },
        "recommended": "NCIS, Law & Order, Criminal Minds, Big Bang Theory, HIMYM, Blue Bloods",
        "color": "blue",
    },
    {
        "number": 102, "name": "Galaxy Premium", "tier": "Galaxy Main",
        "vibe": "Elevated cable drama", "mode": "Flex",
        "style": "AMC/FX energy — prestige-adjacent but accessible",
        "dayparts": {
            "Early Morning (6-9AM)": "Character-driven drama films",
            "Morning (9AM-12PM)": "Limited series / miniseries",
            "Afternoon (12-5PM)": "Serialized drama marathon",
            "Prime Time (5-10PM)": "FLAGSHIP DRAMA — best serialized series",
            "Late Night (10PM-2AM)": "Intense drama, gritty series",
            "Overnight (2-6AM)": "Encore of prime time block",
        },
        "recommended": "Ozark, Yellowstone, The Americans, Justified, Peaky Blinders, Better Call Saul",
        "color": "blue",
    },
    {
        "number": 103, "name": "Galaxy Action", "tier": "Galaxy Main",
        "vibe": "Adrenaline / Franchise", "mode": "Shuffle",
        "style": "Big, loud, fun. Franchise-driven. The popcorn channel.",
        "dayparts": {
            "Early Morning (6-9AM)": "Sci-fi series episodes",
            "Morning (9AM-12PM)": "Superhero block (MCU/DC movies & series)",
            "Afternoon (12-5PM)": "Action movie marathon",
            "Prime Time (5-10PM)": "BLOCKBUSTER ACTION + franchise premieres",
            "Late Night (10PM-2AM)": "R-rated action, intense thrillers",
            "Overnight (2-6AM)": "Sci-fi series marathon",
        },
        "recommended": "MCU, Fast & Furious, Mission Impossible, John Wick, Bond, Bourne, Top Gun, Star Wars",
        "color": "blue",
    },
    {
        "number": 104, "name": "Galaxy Thrills", "tier": "Galaxy Main",
        "vibe": "Tension / Dark energy", "mode": "Shuffle",
        "style": "Morning = suspense. Night = full horror. Escalates through the day.",
        "dayparts": {
            "Early Morning (6-9AM)": "Psychological thrillers (light)",
            "Morning (9AM-12PM)": "Suspense films, slow-burn tension",
            "Afternoon (12-5PM)": "Horror movie block",
            "Prime Time (5-10PM)": "THRILLER/HORROR premieres + suspense series",
            "Late Night (10PM-2AM)": "Peak intensity — creature features, dark horror",
            "Overnight (2-6AM)": "Atmospheric horror, slow burns",
        },
        "recommended": "Se7en, Silence of the Lambs, Gone Girl, A Quiet Place, Get Out, Hereditary, AHS",
        "color": "blue",
    },
    {
        "number": 105, "name": "Galaxy Crime", "tier": "Galaxy Main",
        "vibe": "Investigation / Obsession", "mode": "Flex",
        "style": "Bingeable cases and cops. Obsessive, detail-driven 'one more episode' energy.",
        "dayparts": {
            "Early Morning (6-9AM)": "True crime documentaries",
            "Morning (9AM-12PM)": "Mystery series (whodunits, detective shows)",
            "Afternoon (12-5PM)": "Crime film double feature",
            "Prime Time (5-10PM)": "FLAGSHIP CRIME DRAMA + true crime premieres",
            "Late Night (10PM-2AM)": "Intense crime (The Wire, Mindhunter, dark cases)",
            "Overnight (2-6AM)": "True crime docs, cold case reruns",
        },
        "recommended": "True Detective, Mindhunter, The Wire, Fargo, Zodiac, Prisoners, Heat",
        "color": "blue",
    },
    {
        "number": 106, "name": "Galaxy Romance", "tier": "Galaxy Main",
        "vibe": "Cozy / Emotional", "mode": "Shuffle",
        "style": "Feelings-first. Light mornings, epic love stories at prime, steamy late night.",
        "dayparts": {
            "Early Morning (6-9AM)": "Classic romance films",
            "Morning (9AM-12PM)": "Rom-com block (light and fun)",
            "Afternoon (12-5PM)": "Romance series marathon (Bridgerton, Outlander)",
            "Prime Time (5-10PM)": "FLAGSHIP ROMANCE — epic love stories",
            "Late Night (10PM-2AM)": "Steamy/mature romance, passionate dramas",
            "Overnight (2-6AM)": "Comfort romance reruns, feel-good encores",
        },
        "recommended": "Bridgerton, Outlander, The Notebook, Pride & Prejudice, Crazy Rich Asians",
        "color": "blue",
    },
    {
        "number": 107, "name": "Galaxy Now", "tier": "Galaxy Main",
        "vibe": "Modern / Trending / Competitive", "mode": "Shuffle",
        "style": "Buzz and chaos. Channel surfing energy. Always something happening.",
        "dayparts": {
            "Early Morning (6-9AM)": "Game show reruns",
            "Morning (9AM-12PM)": "Cooking competitions (MasterChef, Hell's Kitchen)",
            "Afternoon (12-5PM)": "Reality competition marathon (Survivor, Amazing Race)",
            "Prime Time (5-10PM)": "PRIME REALITY — competitions + talent shows",
            "Late Night (10PM-2AM)": "Guilty pleasure reality, dating shows",
            "Overnight (2-6AM)": "Reruns, competition encores",
        },
        "recommended": "Survivor, Amazing Race, MasterChef, Hell's Kitchen, The Voice, The Bachelor",
        "color": "blue",
    },
    {
        "number": 108, "name": "Galaxy Comedy", "tier": "Galaxy Main",
        "vibe": "Light / Rewatchable", "mode": "Shuffle",
        "style": "Easy laughs all day. Classic mornings, movies afternoon, stand-up headliner at prime.",
        "dayparts": {
            "Early Morning (6-9AM)": "Classic sitcoms (Seinfeld, Friends)",
            "Morning (9AM-12PM)": "Modern sitcoms (The Office, Parks & Rec, B99)",
            "Afternoon (12-5PM)": "Comedy movie block",
            "Prime Time (5-10PM)": "BEST SITCOMS + comedy film + stand-up headliner",
            "Late Night (10PM-2AM)": "Adult comedy (Always Sunny, Curb) + stand-up",
            "Overnight (2-6AM)": "Sitcom reruns, stand-up marathon",
        },
        "recommended": "The Office, Parks & Rec, Seinfeld, Friends, Brooklyn Nine-Nine, Schitt's Creek",
        "color": "blue",
    },
    {
        "number": 109, "name": "Galaxy Puerto Rico", "tier": "Galaxy Main",
        "vibe": "Cultural / Regional", "mode": "Shuffle",
        "style": "Island identity and community. Music-heavy. Cultural pride all day.",
        "dayparts": {
            "Early Morning (6-9AM)": "Music videos (salsa, bomba y plena)",
            "Morning (9AM-12PM)": "Cultural documentaries, island history",
            "Afternoon (12-5PM)": "Puerto Rican films & comedies",
            "Prime Time (5-10PM)": "BEST PR FILMS, music specials, cultural showcases",
            "Late Night (10PM-2AM)": "Reggaeton/urban music content, concerts",
            "Overnight (2-6AM)": "Music rotation (salsa, jibaro, old-school)",
        },
        "recommended": "PR cinema, Latin American films, Daddy Yankee, Bad Bunny, Hector Lavoe",
        "color": "blue",
    },
    {
        "number": 110, "name": "Galaxy Yaideliz", "tier": "Galaxy Main",
        "vibe": "Personal / Curated", "mode": "Sequential",
        "style": "Your channel, your rules. No formula. Pure taste. Update frequently.",
        "dayparts": {
            "All Day": "Curated personal mix — rotate as desired",
        },
        "recommended": "Whatever the curator loves. Blank canvas — theme by mood, season, or taste.",
        "color": "blue",
    },
    {
        "number": 112, "name": "Galaxy Kids", "tier": "Galaxy Main",
        "vibe": "Bright / Parent-safe", "mode": "Shuffle",
        "style": "Parent-safe 24/7. Preschool mornings, big movies at night. Nothing scary.",
        "dayparts": {
            "Early Morning (6-9AM)": "Preschool animation (Bluey, Peppa Pig)",
            "Morning (9AM-12PM)": "Animated series (SpongeBob, Gravity Falls)",
            "Afternoon (12-5PM)": "Animated movie block (Pixar, DreamWorks, Disney)",
            "Prime Time (5-10PM)": "FAMILY MOVIE NIGHT — live-action + animated features",
            "Late Night (10PM-2AM)": "Older kids/teen content (Avatar, adventure series)",
            "Overnight (2-6AM)": "Calm/relaxing content",
        },
        "recommended": "Pixar, DreamWorks, Disney animated, Bluey, SpongeBob, Avatar: The Last Airbender",
        "color": "blue",
    },
    {
        "number": 113, "name": "Galaxy Toons", "tier": "Galaxy Main",
        "vibe": "All-ages cartoon fun", "mode": "Shuffle",
        "style": "Catch-all cartoon channel. Lighter and broader than Animated. Pure toon energy.",
        "dayparts": {
            "Early Morning (6-9AM)": "Morning cartoons (Looney Tunes, Tom & Jerry)",
            "Morning (9AM-12PM)": "Nickelodeon/CN crossover hits",
            "Afternoon (12-5PM)": "Cartoon marathon block",
            "Prime Time (5-10PM)": "TOONS PRIME — best episodes across all eras",
            "Late Night (10PM-2AM)": "Edgier animated comedies (Futurama, Bob's Burgers)",
            "Overnight (2-6AM)": "Classic shorts, cartoon reruns",
        },
        "recommended": "Looney Tunes, Futurama, Bob's Burgers, King of the Hill, Animaniacs",
        "color": "blue",
    },
    {
        "number": 114, "name": "Galaxy WBToons", "tier": "Galaxy Main",
        "vibe": "WB cartoon legacy / DCAU", "mode": "Shuffle",
        "style": "Full WB animation legacy. Looney Tunes mornings, Kids' WB midday, DCAU at night.",
        "dayparts": {
            "Early Morning (6-9AM)": "Looney Tunes shorts block",
            "Morning (9AM-12PM)": "Saturday morning energy (Animaniacs, Tiny Toons)",
            "Afternoon (12-5PM)": "WB animation marathon",
            "Prime Time (5-10PM)": "WB TOONS PRIME — flagship series, best episodes",
            "Late Night (10PM-2AM)": "Batman/Superman animated universe block",
            "Overnight (2-6AM)": "Classic Looney Tunes rotation",
        },
        "recommended": "Batman TAS, Superman TAS, Animaniacs, Tiny Toon Adventures, Pinky and the Brain",
        "color": "blue",
    },
    {
        "number": 115, "name": "Galaxy Animated", "tier": "Galaxy Main",
        "vibe": "Stylized storytelling", "mode": "Flex",
        "style": "Day = family-friendly animation. Night = adult animation, anime, mature storytelling.",
        "dayparts": {
            "Early Morning (6-9AM)": "Family animated films (Pixar, DreamWorks)",
            "Morning (9AM-12PM)": "Animated series marathon",
            "Afternoon (12-5PM)": "Animated movie double feature",
            "Prime Time (5-10PM)": "FLAGSHIP ANIMATION — best films + series",
            "Late Night (10PM-2AM)": "Adult animation block (Arcane, Invincible, anime)",
            "Overnight (2-6AM)": "Animated film rotation",
        },
        "recommended": "Spider-Verse, Miyazaki, Arcane, Invincible, Castlevania, Cowboy Bebop",
        "color": "blue",
    },

    {
        "number": 116, "name": "Galaxy Anime", "tier": "Galaxy Main",
        "vibe": "Anime / Japanese animation", "mode": "Flex",
        "style": "Shonen energy during the day, deeper mature titles after 10PM. Anime-only channel.",
        "dayparts": {
            "Early Morning (6-9AM)": "Classic shonen (Naruto, DBZ, One Piece)",
            "Morning (9AM-12PM)": "Action/adventure anime block",
            "Afternoon (12-5PM)": "Anime marathon (mix of genres)",
            "Prime Time (5-10PM)": "ANIME PRIME — flagship series + films",
            "Late Night (10PM-2AM)": "Seinen block — mature, psychological, dark",
            "Overnight (2-6AM)": "Anime film rotation",
        },
        "recommended": "Attack on Titan, Demon Slayer, FMA Brotherhood, Death Note, Cowboy Bebop, Akira",
        "color": "blue",
    },

    # ── Classics ─────────────────────────────────────────────────
    {
        "number": 120, "name": "Cartoon Network", "tier": "Classics",
        "vibe": "90s/00s cartoon energy", "mode": "Shuffle",
        "style": "CN golden era — Dexter's Lab through Adventure Time.",
        "dayparts": {
            "Early Morning (6-9AM)": "Classic cartoons, lighter fare",
            "Morning (9AM-12PM)": "Kids animation (Adventure Time, Regular Show, SU)",
            "Afternoon (12-5PM)": "Action cartoons (Ben 10, Samurai Jack)",
            "Prime Time (5-10PM)": "FLAGSHIP SHOWS (Dexter's Lab, PPG, modern hits)",
            "Late Night (10PM-2AM)": "Adult-leaning animation (transition to AS style)",
            "Overnight (2-6AM)": "Reruns, classic episodes",
        },
        "recommended": "Dexter's Lab, Powerpuff Girls, Adventure Time, Regular Show, Steven Universe, Ed Edd n Eddy",
        "color": "amber",
    },
    {
        "number": 121, "name": "Boomerang", "tier": "Classics",
        "vibe": "Retro Hanna-Barbera classics", "mode": "Shuffle",
        "style": "Pure nostalgia archive. Nothing post-2000. Grandparent-safe and childhood-core.",
        "dayparts": {
            "Early Morning (6-9AM)": "Morning classics (Tom & Jerry, Looney Tunes)",
            "Morning (9AM-12PM)": "Hanna-Barbera block (Flintstones, Yogi Bear, Jetsons)",
            "Afternoon (12-5PM)": "Classic cartoon marathon",
            "Prime Time (5-10PM)": "RETRO PRIME — golden age cartoons",
            "Late Night (10PM-2AM)": "Late-night classics, obscure Hanna-Barbera",
            "Overnight (2-6AM)": "Classic shorts rotation",
        },
        "recommended": "The Flintstones, The Jetsons, Yogi Bear, Scooby-Doo, Top Cat, Huckleberry Hound",
        "color": "amber",
    },
    {
        "number": 122, "name": "Disney Channel", "tier": "Classics",
        "vibe": "Tween nostalgia / wholesome", "mode": "Shuffle",
        "style": "DCOMs prime time, sitcom afternoons, animated mornings.",
        "dayparts": {
            "Early Morning (6-9AM)": "Disney Junior content (Bluey, Doc McStuffins)",
            "Morning (9AM-12PM)": "Animated series (Phineas & Ferb, Amphibia, Owl House)",
            "Afternoon (12-5PM)": "Sitcom block (Jessie, Good Luck Charlie)",
            "Prime Time (5-10PM)": "DCOMs + FLAGSHIP SERIES (HSM, Descendants)",
            "Late Night (10PM-2AM)": "Teen-oriented sitcoms, older Disney Channel",
            "Overnight (2-6AM)": "Reruns, classic DCOMs",
        },
        "recommended": "High School Musical, Descendants, Halloweentown, Wizards of Waverly Place, Phineas & Ferb",
        "color": "amber",
    },
    {
        "number": 123, "name": "Disney XD", "tier": "Classics",
        "vibe": "Action-adventure toons", "mode": "Shuffle",
        "style": "Boy-skewing action and adventure. More kinetic and plot-driven than Disney Channel.",
        "dayparts": {
            "Early Morning (6-9AM)": "Morning adventure cartoons",
            "Morning (9AM-12PM)": "Action/comedy animated block",
            "Afternoon (12-5PM)": "Marathon block (DuckTales, Gravity Falls)",
            "Prime Time (5-10PM)": "FLAGSHIP ACTION — best series, event episodes",
            "Late Night (10PM-2AM)": "Older-skewing action and sci-fi animation",
            "Overnight (2-6AM)": "Reruns, classic episodes",
        },
        "recommended": "Gravity Falls, DuckTales (2017), Star Wars Rebels, Big Hero 6: The Series, Tron: Uprising",
        "color": "amber",
    },
    {
        "number": 124, "name": "Nickelodeon", "tier": "Classics",
        "vibe": "Slime-era kids channel", "mode": "Shuffle",
        "style": "Nick Jr. mornings, Nicktoons midday, live-action afternoon, Avatar late night.",
        "dayparts": {
            "Early Morning (6-9AM)": "Nick Jr. / preschool (Blue's Clues, Dora)",
            "Morning (9AM-12PM)": "Nicktoons (SpongeBob, Fairly OddParents, Danny Phantom)",
            "Afternoon (12-5PM)": "Live-action block (iCarly, Drake & Josh, Victorious)",
            "Prime Time (5-10PM)": "BEST-OF MIX — top animated + live-action",
            "Late Night (10PM-2AM)": "Teen/older Nick (Avatar, Korra, AYAOTD?)",
            "Overnight (2-6AM)": "Reruns, classic episodes",
        },
        "recommended": "SpongeBob, Avatar: The Last Airbender, iCarly, Drake & Josh, Rugrats, Hey Arnold!",
        "color": "amber",
    },
    {
        "number": 125, "name": "Nicktoons", "tier": "Classics",
        "vibe": "Nick animation deep cuts", "mode": "Shuffle",
        "style": "Animation-only Nick. No live-action. Pure Nicktoons catalog — deep cuts and fan favorites.",
        "dayparts": {
            "Early Morning (6-9AM)": "Early Nick classics (Rugrats, Hey Arnold!)",
            "Morning (9AM-12PM)": "90s Nicktoons golden era",
            "Afternoon (12-5PM)": "Animation marathon (deep catalog)",
            "Prime Time (5-10PM)": "NICKTOONS PRIME — fan favorites + cult classics",
            "Late Night (10PM-2AM)": "Edgier Nick (Invader Zim, Ren & Stimpy, AYAOTD?)",
            "Overnight (2-6AM)": "Classic Nicktoons reruns",
        },
        "recommended": "Rugrats, Invader Zim, Rocko's Modern Life, Danny Phantom, Ren & Stimpy, CatDog",
        "color": "amber",
    },
    {
        "number": 126, "name": "MTV", "tier": "Classics",
        "vibe": "Youth culture / Music", "mode": "Shuffle",
        "style": "Buzz and chaos. TRL energy. Music videos to reality TV to Jackass.",
        "dayparts": {
            "Early Morning (6-9AM)": "Music video blocks (rotation by decade)",
            "Morning (9AM-12PM)": "TRL-style countdown blocks",
            "Afternoon (12-5PM)": "Reality TV block (Real World, Cribs, Road Rules)",
            "Prime Time (5-10PM)": "FLAGSHIP REALITY + music specials (Unplugged, VMAs)",
            "Late Night (10PM-2AM)": "Beavis & Butt-Head, Jackass, edgier content",
            "Overnight (2-6AM)": "Music video marathon",
        },
        "recommended": "The Real World, Jackass, Cribs, Punk'd, Jersey Shore, Beavis & Butt-Head, Daria",
        "color": "amber",
    },

    # ── Galaxy Premium ────────────────────────────────────────────
    {
        "number": 140, "name": "Galaxy Premieres", "tier": "Galaxy Premium",
        "vibe": "Prestige / Event TV", "mode": "Flex",
        "style": "HBO flagship energy. Everything should feel like an event. Only the best.",
        "dayparts": {
            "Early Morning (6-9AM)": "Acclaimed indie films",
            "Morning (9AM-12PM)": "Limited series / miniseries",
            "Afternoon (12-5PM)": "Award-winning film block",
            "Prime Time (5-10PM)": "PRESTIGE PREMIERES — best of the best",
            "Late Night (10PM-2AM)": "Critically acclaimed drama, art house films",
            "Overnight (2-6AM)": "Encore of prime time block",
        },
        "recommended": "Parasite, Moonlight, Breaking Bad, The Wire, Sopranos, Succession, Chernobyl",
        "color": "purple",
    },
    {
        "number": 141, "name": "Galaxy Cinema", "tier": "Galaxy Premium",
        "vibe": "Pure movies", "mode": "Flex",
        "style": "The all-day movie channel. Wide variety, well-slotted by time of day.",
        "dayparts": {
            "Early Morning (6-9AM)": "Feel-good movies, comedies",
            "Morning (9AM-12PM)": "Action/adventure films",
            "Afternoon (12-5PM)": "Double feature block (themed pairings)",
            "Prime Time (5-10PM)": "BLOCKBUSTER PREMIERE SLOT",
            "Late Night (10PM-2AM)": "Thriller/suspense films",
            "Overnight (2-6AM)": "Encore rotation",
        },
        "recommended": "Everything cinematic — director spotlights, decade marathons, genre deep dives",
        "color": "purple",
    },
    {
        "number": 142, "name": "Galaxy Hits", "tier": "Galaxy Premium",
        "vibe": "Crowd-pleasers", "mode": "Shuffle",
        "style": "Movies everyone has seen and wants to see again. Pure comfort blockbusters.",
        "dayparts": {
            "Early Morning (6-9AM)": "Feel-good hits (Forrest Gump, Princess Bride)",
            "Morning (9AM-12PM)": "Fan-favorites (Back to the Future, Indiana Jones)",
            "Afternoon (12-5PM)": "Crowd-pleaser double feature",
            "Prime Time (5-10PM)": "BIGGEST HITS — the movies everyone loves",
            "Late Night (10PM-2AM)": "Rewatchable action/thriller hits",
            "Overnight (2-6AM)": "Encore rotation",
        },
        "recommended": "Shawshank Redemption, Forrest Gump, The Dark Knight, Jurassic Park, Inception",
        "color": "purple",
    },
    {
        "number": 143, "name": "Galaxy Thriller", "tier": "Galaxy Premium",
        "vibe": "Suspense / Edge", "mode": "Shuffle",
        "style": "Premium tension. Smarter, slower-burn than Galaxy Thrills. Films that reward attention.",
        "dayparts": {
            "Early Morning (6-9AM)": "Espionage / spy thrillers",
            "Morning (9AM-12PM)": "Crime films (heist, detective)",
            "Afternoon (12-5PM)": "Thriller double feature",
            "Prime Time (5-10PM)": "FLAGSHIP THRILLERS — premium suspense",
            "Late Night (10PM-2AM)": "Dark thrillers, neo-noir, intense crime",
            "Overnight (2-6AM)": "Encore rotation",
        },
        "recommended": "No Country for Old Men, Sicario, Heat, Drive, Collateral, Nightcrawler",
        "color": "purple",
    },
    {
        "number": 144, "name": "Galaxy Vault", "tier": "Galaxy Premium",
        "vibe": "Timeless / Library prestige", "mode": "Shuffle",
        "style": "Heritage cinema. Pre-2000 only. Black & white welcome. Prestige and history.",
        "dayparts": {
            "Early Morning (6-9AM)": "Golden age classics (black & white era)",
            "Morning (9AM-12PM)": "70s/80s acclaimed films",
            "Afternoon (12-5PM)": "Classic film double feature",
            "Prime Time (5-10PM)": "TIMELESS MASTERPIECES — the greatest films ever made",
            "Late Night (10PM-2AM)": "Film noir, classic thrillers, Hitchcock",
            "Overnight (2-6AM)": "Black & white film rotation",
        },
        "recommended": "The Godfather, Casablanca, Pulp Fiction, Goodfellas, Blade Runner, 2001: A Space Odyssey",
        "color": "purple",
    },
    {
        "number": 145, "name": "Galaxy After Dark", "tier": "Galaxy Premium",
        "vibe": "Mature / Bold", "mode": "Shuffle",
        "style": "Late-night freedom. The channel where anything goes. Peak hours 10PM-4AM.",
        "dayparts": {
            "Early Morning (6-9AM)": "Off-air or light mature comedies",
            "Morning (9AM-12PM)": "Cult classics, B-movies",
            "Afternoon (12-5PM)": "Mature drama films",
            "Prime Time (5-10PM)": "R-RATED MOVIE PREMIERES",
            "Late Night (10PM-2AM)": "Peak programming — adult content, provocative films",
            "Overnight (2-6AM)": "Midnight movie marathon",
        },
        "recommended": "Wolf of Wall Street, Deadpool, Boogie Nights, Eyes Wide Shut, Requiem for a Dream",
        "color": "purple",
    },
]

CHANNELS_BY_NUMBER = {ch["number"]: ch for ch in CHANNELS}
