// Curated real-world network presets for one-click channel creation.
// Picking a preset auto-fills the channel form with name, tier, vibe, mode, style, color.

export type NetworkCategory =
  | 'Kids'
  | 'Family'
  | 'Adult Animation'
  | 'Premium'
  | 'Drama'
  | 'Network TV'
  | 'Cable Drama'
  | 'Comedy'
  | 'Movies'
  | 'Sci-Fi & Action'
  | 'Lifestyle & Reality'
  | 'Music'
  | 'News & Info'
  | 'Sports'

export interface NetworkPreset {
  id: string
  name: string
  category: NetworkCategory
  tier: 'Galaxy Main' | 'Classics' | 'Galaxy Premium'
  vibe: string
  mode: 'Shuffle' | 'Flex' | 'Sequential'
  style: string
  color: string // tailwind color name (blue, amber, purple, red, green, yellow, pink, etc)
}

export const NETWORK_PRESETS: NetworkPreset[] = [
  // ── Kids ──
  {
    id: 'cartoon-network',
    name: 'Cartoon Network',
    category: 'Kids',
    tier: 'Classics',
    vibe: '90s/00s cartoon energy',
    mode: 'Shuffle',
    style: "CN golden era — Dexter's Lab through Adventure Time.",
    color: 'amber',
  },
  {
    id: 'boomerang',
    name: 'Boomerang',
    category: 'Kids',
    tier: 'Classics',
    vibe: 'Retro Hanna-Barbera classics',
    mode: 'Shuffle',
    style: 'Pure nostalgia archive. Nothing post-2000. Grandparent-safe and childhood-core.',
    color: 'amber',
  },
  {
    id: 'disney-channel',
    name: 'Disney Channel',
    category: 'Kids',
    tier: 'Classics',
    vibe: 'Tween nostalgia / wholesome',
    mode: 'Shuffle',
    style: 'DCOMs prime time, sitcom afternoons, animated mornings.',
    color: 'blue',
  },
  {
    id: 'disney-xd',
    name: 'Disney XD',
    category: 'Kids',
    tier: 'Classics',
    vibe: 'Action-adventure toons',
    mode: 'Shuffle',
    style: 'Boy-skewing action and adventure. More kinetic and plot-driven than Disney Channel.',
    color: 'blue',
  },
  {
    id: 'disney-junior',
    name: 'Disney Junior',
    category: 'Kids',
    tier: 'Classics',
    vibe: 'Bright / Parent-safe',
    mode: 'Shuffle',
    style:
      'Preschool-focused. Bright, gentle, educational. Mickey Mouse Clubhouse to Doc McStuffins.',
    color: 'pink',
  },
  {
    id: 'nickelodeon',
    name: 'Nickelodeon',
    category: 'Kids',
    tier: 'Classics',
    vibe: 'Slime-era kids channel',
    mode: 'Shuffle',
    style: 'Nick Jr. mornings, Nicktoons midday, live-action afternoon, Avatar late night.',
    color: 'orange',
  },
  {
    id: 'nick-jr',
    name: 'Nick Jr.',
    category: 'Kids',
    tier: 'Classics',
    vibe: 'Bright / Parent-safe',
    mode: 'Shuffle',
    style: "Preschool 24/7. Blue's Clues, Dora, Paw Patrol — gentle and educational.",
    color: 'sky',
  },
  {
    id: 'nicktoons',
    name: 'Nicktoons',
    category: 'Kids',
    tier: 'Classics',
    vibe: 'Nick animation deep cuts',
    mode: 'Shuffle',
    style:
      'Animation-only Nick. No live-action. Pure Nicktoons catalog — deep cuts and fan favorites.',
    color: 'orange',
  },
  {
    id: 'pbs-kids',
    name: 'PBS Kids',
    category: 'Kids',
    tier: 'Classics',
    vibe: 'Bright / Parent-safe',
    mode: 'Shuffle',
    style: 'Educational and gentle. Sesame Street, Daniel Tiger, Curious George, Wild Kratts.',
    color: 'green',
  },

  // ── Family ──
  {
    id: 'hub',
    name: 'Hub Network',
    category: 'Family',
    tier: 'Classics',
    vibe: 'All-ages cartoon fun',
    mode: 'Shuffle',
    style: 'Family co-viewing. Mix of toons and live-action with broad appeal.',
    color: 'purple',
  },
  {
    id: 'freeform',
    name: 'Freeform',
    category: 'Family',
    tier: 'Galaxy Main',
    vibe: 'Tween nostalgia / wholesome',
    mode: 'Shuffle',
    style: 'Older-tween / young adult. Family movies, teen dramas, holiday specials.',
    color: 'pink',
  },

  // ── Adult Animation ──
  {
    id: 'adult-swim',
    name: 'Adult Swim',
    category: 'Adult Animation',
    tier: 'Galaxy Premium',
    vibe: 'Mature / Bold',
    mode: 'Shuffle',
    style: 'Late-night freedom. The channel where anything goes. Peak hours 10PM-4AM.',
    color: 'gray',
  },
  {
    id: 'comedy-central',
    name: 'Comedy Central',
    category: 'Comedy',
    tier: 'Galaxy Main',
    vibe: 'Light / Rewatchable',
    mode: 'Shuffle',
    style: 'Easy laughs all day. Classic mornings, movies afternoon, stand-up headliner at prime.',
    color: 'yellow',
  },

  // ── Premium ──
  {
    id: 'hbo',
    name: 'HBO',
    category: 'Premium',
    tier: 'Galaxy Premium',
    vibe: 'Prestige / Event TV',
    mode: 'Flex',
    style: 'HBO flagship energy. Everything should feel like an event. Only the best.',
    color: 'purple',
  },
  {
    id: 'showtime',
    name: 'Showtime',
    category: 'Premium',
    tier: 'Galaxy Premium',
    vibe: 'Mature / Bold',
    mode: 'Flex',
    style: 'Edgier prestige. Boundary-pushing drama and limited series.',
    color: 'red',
  },
  {
    id: 'starz',
    name: 'Starz',
    category: 'Premium',
    tier: 'Galaxy Premium',
    vibe: 'Mature / Bold',
    mode: 'Flex',
    style: 'Bold storytelling. Mature drama with cinematic ambition.',
    color: 'rose',
  },
  {
    id: 'cinemax',
    name: 'Cinemax',
    category: 'Movies',
    tier: 'Galaxy Premium',
    vibe: 'Suspense / Edge',
    mode: 'Flex',
    style: 'Late-night thrillers and action movies. Genre-forward.',
    color: 'amber',
  },
  {
    id: 'epix',
    name: 'Epix',
    category: 'Movies',
    tier: 'Galaxy Premium',
    vibe: 'Pure movies',
    mode: 'Shuffle',
    style: 'Recent box office and prestige films. Movies-first programming.',
    color: 'indigo',
  },

  // ── Drama / Prestige Cable ──
  {
    id: 'amc',
    name: 'AMC',
    category: 'Drama',
    tier: 'Galaxy Main',
    vibe: 'Elevated cable drama',
    mode: 'Flex',
    style: 'AMC/FX energy — prestige-adjacent but accessible.',
    color: 'red',
  },
  {
    id: 'fx',
    name: 'FX',
    category: 'Drama',
    tier: 'Galaxy Main',
    vibe: 'Elevated cable drama',
    mode: 'Flex',
    style: 'Sharp, ambitious cable drama. Anthology-friendly. Premium feel.',
    color: 'orange',
  },
  {
    id: 'fxx',
    name: 'FXX',
    category: 'Comedy',
    tier: 'Galaxy Main',
    vibe: 'Light / Rewatchable',
    mode: 'Shuffle',
    style: 'Comedy-forward FX spinoff. Always Sunny, Archer, animation block.',
    color: 'orange',
  },

  // ── Network TV ──
  {
    id: 'nbc',
    name: 'NBC',
    category: 'Network TV',
    tier: 'Galaxy Main',
    vibe: 'Crowd-pleasers',
    mode: 'Shuffle',
    style: 'Mainstream broadcast network. Sitcoms, procedurals, primetime drama.',
    color: 'blue',
  },
  {
    id: 'cbs',
    name: 'CBS',
    category: 'Network TV',
    tier: 'Galaxy Main',
    vibe: 'Cozy crime procedurals',
    mode: 'Shuffle',
    style: "Bingeable cases and cops. Obsessive, detail-driven 'one more episode' energy.",
    color: 'sky',
  },
  {
    id: 'abc',
    name: 'ABC',
    category: 'Network TV',
    tier: 'Galaxy Main',
    vibe: 'Crowd-pleasers',
    mode: 'Shuffle',
    style: 'Family-friendly network programming. Comedy + drama mix.',
    color: 'red',
  },
  {
    id: 'fox',
    name: 'FOX',
    category: 'Network TV',
    tier: 'Galaxy Main',
    vibe: 'Crowd-pleasers',
    mode: 'Shuffle',
    style: 'Animation Domination, primetime drama, broad-appeal entertainment.',
    color: 'indigo',
  },
  {
    id: 'cw',
    name: 'The CW',
    category: 'Network TV',
    tier: 'Galaxy Main',
    vibe: 'Tween nostalgia / wholesome',
    mode: 'Shuffle',
    style: 'Young-adult drama, superhero shows, teen-skewing programming.',
    color: 'green',
  },

  // ── Cable Drama / Lifestyle ──
  {
    id: 'tnt',
    name: 'TNT',
    category: 'Cable Drama',
    tier: 'Galaxy Main',
    vibe: 'Adrenaline / Franchise',
    mode: 'Shuffle',
    style: 'Big, loud, fun. Franchise-driven. The popcorn channel.',
    color: 'red',
  },
  {
    id: 'tbs',
    name: 'TBS',
    category: 'Comedy',
    tier: 'Galaxy Main',
    vibe: 'Light / Rewatchable',
    mode: 'Shuffle',
    style: 'Sitcom reruns and comedy movies. Weeknight wind-down.',
    color: 'yellow',
  },
  {
    id: 'usa',
    name: 'USA Network',
    category: 'Cable Drama',
    tier: 'Galaxy Main',
    vibe: 'Cozy crime procedurals',
    mode: 'Shuffle',
    style: 'Blue Sky procedurals. Light crime, comedy-drama, easy bingeable shows.',
    color: 'blue',
  },
  {
    id: 'ae',
    name: 'A&E',
    category: 'Lifestyle & Reality',
    tier: 'Galaxy Main',
    vibe: 'Investigation / Obsession',
    mode: 'Shuffle',
    style: 'True crime documentaries and reality programming.',
    color: 'gray',
  },
  {
    id: 'bravo',
    name: 'Bravo',
    category: 'Lifestyle & Reality',
    tier: 'Galaxy Main',
    vibe: 'Modern / Trending / Competitive',
    mode: 'Shuffle',
    style: 'Reality TV powerhouse. Real Housewives, Top Chef, competitive reality.',
    color: 'pink',
  },
  {
    id: 'lifetime',
    name: 'Lifetime',
    category: 'Lifestyle & Reality',
    tier: 'Galaxy Main',
    vibe: 'Cozy / Emotional',
    mode: 'Shuffle',
    style: 'Feelings-first. Light mornings, epic love stories at prime, steamy late night.',
    color: 'rose',
  },
  {
    id: 'paramount',
    name: 'Paramount Network',
    category: 'Drama',
    tier: 'Galaxy Main',
    vibe: 'Adrenaline / Franchise',
    mode: 'Shuffle',
    style: 'Yellowstone-led modern Western and broad-appeal drama.',
    color: 'amber',
  },

  // ── Movies ──
  {
    id: 'tcm',
    name: 'TCM',
    category: 'Movies',
    tier: 'Classics',
    vibe: 'Timeless / Library prestige',
    mode: 'Sequential',
    style: 'Heritage cinema. Pre-2000 only. Black & white welcome. Prestige and history.',
    color: 'gray',
  },
  {
    id: 'amc-movies',
    name: 'AMC Movies',
    category: 'Movies',
    tier: 'Galaxy Main',
    vibe: 'Pure movies',
    mode: 'Shuffle',
    style: 'The all-day movie channel. Wide variety, well-slotted by time of day.',
    color: 'red',
  },
  {
    id: 'ifc',
    name: 'IFC',
    category: 'Movies',
    tier: 'Galaxy Premium',
    vibe: 'Personal / Curated',
    mode: 'Flex',
    style: 'Indie film and offbeat comedy. Cult cinema, festival-circuit films.',
    color: 'purple',
  },
  {
    id: 'sundance',
    name: 'Sundance TV',
    category: 'Drama',
    tier: 'Galaxy Premium',
    vibe: 'Stylized storytelling',
    mode: 'Flex',
    style: 'Independent prestige. Slow-burn drama, international cinema.',
    color: 'orange',
  },

  // ── Sci-Fi & Action ──
  {
    id: 'syfy',
    name: 'SyFy',
    category: 'Sci-Fi & Action',
    tier: 'Galaxy Main',
    vibe: 'Stylized storytelling',
    mode: 'Shuffle',
    style: 'Sci-fi, fantasy, supernatural. From classics to schlock to prestige.',
    color: 'indigo',
  },
  {
    id: 'chiller',
    name: 'Chiller',
    category: 'Sci-Fi & Action',
    tier: 'Galaxy Premium',
    vibe: 'Tension / Dark energy',
    mode: 'Shuffle',
    style: 'Morning = suspense. Night = full horror. Escalates through the day.',
    color: 'red',
  },

  // ── Lifestyle & Reality ──
  {
    id: 'hgtv',
    name: 'HGTV',
    category: 'Lifestyle & Reality',
    tier: 'Galaxy Main',
    vibe: 'Cozy / Emotional',
    mode: 'Shuffle',
    style: 'Home design, renovation, real estate. Comforting always-on lifestyle.',
    color: 'teal',
  },
  {
    id: 'food-network',
    name: 'Food Network',
    category: 'Lifestyle & Reality',
    tier: 'Galaxy Main',
    vibe: 'Cozy / Emotional',
    mode: 'Shuffle',
    style: 'Cooking shows, food competitions, travel-eat programming.',
    color: 'amber',
  },
  {
    id: 'travel-channel',
    name: 'Travel Channel',
    category: 'Lifestyle & Reality',
    tier: 'Galaxy Main',
    vibe: 'Investigation / Obsession',
    mode: 'Shuffle',
    style: 'Travel docs by day, paranormal/mystery at night.',
    color: 'green',
  },
  {
    id: 'discovery',
    name: 'Discovery',
    category: 'Lifestyle & Reality',
    tier: 'Galaxy Main',
    vibe: 'Investigation / Obsession',
    mode: 'Shuffle',
    style: 'Documentary and reality. Science, nature, adventure, deep-dive series.',
    color: 'blue',
  },
  {
    id: 'history',
    name: 'History Channel',
    category: 'Lifestyle & Reality',
    tier: 'Galaxy Main',
    vibe: 'Investigation / Obsession',
    mode: 'Shuffle',
    style: 'Documentary, military history, reality docu-series.',
    color: 'amber',
  },
  {
    id: 'animal-planet',
    name: 'Animal Planet',
    category: 'Lifestyle & Reality',
    tier: 'Galaxy Main',
    vibe: 'Cozy / Emotional',
    mode: 'Shuffle',
    style: 'Wildlife docs, pet shows, animal rescue programming.',
    color: 'green',
  },
  {
    id: 'nat-geo',
    name: 'National Geographic',
    category: 'Lifestyle & Reality',
    tier: 'Galaxy Main',
    vibe: 'Stylized storytelling',
    mode: 'Flex',
    style: 'Premium documentary. Nature, science, cultural exploration.',
    color: 'yellow',
  },

  // ── Music ──
  {
    id: 'mtv',
    name: 'MTV',
    category: 'Music',
    tier: 'Classics',
    vibe: 'Youth culture / Music',
    mode: 'Shuffle',
    style: 'Buzz and chaos. TRL energy. Music videos to reality TV to Jackass.',
    color: 'pink',
  },
  {
    id: 'vh1',
    name: 'VH1',
    category: 'Music',
    tier: 'Classics',
    vibe: 'Youth culture / Music',
    mode: 'Shuffle',
    style: 'Pop nostalgia, music documentaries, reality music shows.',
    color: 'orange',
  },
  {
    id: 'bet',
    name: 'BET',
    category: 'Music',
    tier: 'Galaxy Main',
    vibe: 'Cultural / Regional',
    mode: 'Shuffle',
    style: 'Black entertainment programming. Music, comedy, drama, awards.',
    color: 'indigo',
  },
  {
    id: 'cmt',
    name: 'CMT',
    category: 'Music',
    tier: 'Galaxy Main',
    vibe: 'Cultural / Regional',
    mode: 'Shuffle',
    style: 'Country music videos, reality, country-themed films.',
    color: 'amber',
  },
]

export const NETWORK_CATEGORIES: NetworkCategory[] = [
  'Kids',
  'Family',
  'Adult Animation',
  'Premium',
  'Drama',
  'Network TV',
  'Cable Drama',
  'Comedy',
  'Movies',
  'Sci-Fi & Action',
  'Lifestyle & Reality',
  'Music',
  'News & Info',
  'Sports',
]
